apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: gcpadmintokens.gcp.compute.hub.appvia.io
spec:
  group: gcp.compute.hub.appvia.io
  names:
    kind: GCPAdminToken
    listKind: GCPAdminTokenList
    plural: gcpadmintokens
    singular: gcpadmintoken
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: GCPAdminToken is the Schema for the gcpadmintokens API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: GCPAdminTokenSpec defines the desired state of GCPAdminToken
          properties:
            organizationId:
              description: Organization is the GCP org you wish the projects to reside
                within
              type: string
            projectId:
              description: ProjectId is the GCP project ID these credentials belong
                to
              type: string
            token:
              description: Token is the bearer token used to setup the initial GCP
                admin project and service account You must grab a token using 'gcloud
                auth print-access-token you@example.com'
              type: string
          required:
          - organizationId
          - projectId
          - token
          type: object
        status:
          description: GCPAdminTokenStatus defines the observed state of GCPAdminToken
          properties:
            status:
              description: Status provides a overall status
              type: string
            verified:
              description: Verified checks that the token is ok and valid
              type: boolean
          required:
          - status
          - verified
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
