apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: gcpadmintokens.gcp.compute.hub.appvia.io
spec:
  group: gcp.compute.hub.appvia.io
  names:
    kind: GCPAdminTokens
    listKind: GCPAdminTokensList
    plural: gcpadmintokens
    singular: gcpadminproject
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: GCPAdminTokens is the Schema for the gcpadmintokens API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: gcpadmintokenspec defines the desired state of GCPAdminTokens
          properties:
            key:
              description: 'Key is the access token used to create the initial GCP admin project,
                generated using `gcloud auth print-access-token you@example.com`'
              type: string
          required:
          - key
          type: object
        status:
          description: gcpadmintokenstatus defines the observed state of GCPAdminTokens
          properties:
            status:
              description: Status provides a overall status
              type: string
            verified:
              description: Verified checks that the token is ok and valid
              type: bool
          required:
          - status
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
