apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: gcpadmintokens.gcp.compute.hub.appvia.io
spec:
  group: gcp.compute.hub.appvia.io
  names:
    kind: GCPAdminToken
    listKind: GCPAdminTokenList
    plural: gcpadmintokens
    singular: gcpadmintoken
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: GCPAdminToken is the Schema for the gcpadmintokens API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: GCPAdminTokenSpec defines the desired state of GCPAdminToken
          properties:
            token:
              description: Token is the bearer token used to setup the initial GCP admin project and service account
              type: string
            projectId:
              description: ProjectId is the GCP project ID these credentials belong to
                has
              type: string
            organizationId:
              description: OrganizationId is the GCP organization these credentials belong to
              type: string
            use:
              description: GCPCredentials is a reference to the gcp credentials object
                to use
              properties:
                group:
                  description: Group is the api group
                  type: string
                kind:
                  description: Kind is the name of the resource under the group
                  type: string
                name:
                  description: Name is name of the resource
                  type: string
                namespace:
                  description: Namespace is the location of the object
                  type: string
                version:
                  description: Version is the group version
                  type: string
              required:
              - group
              - kind
              - name
              - namespace
              - version
              type: object
          required:
          - token
          - projectId
          - organizationId
          - use
          type: object
        status:
          description: GCPAdminTokenStatus defines the observed state of GCPAdminToken
          properties:
            status:
              description: Status provides a overall status
              type: string
          required:
          - status
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
