apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: gcpcredentials.gcp.compute.hub.appvia.io
spec:
  group: gcp.compute.hub.appvia.io
  names:
    kind: GCPCredentials
    listKind: GCPCredentialsList
    plural: gcpcredentials
    singular: gcpcredentials
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: GCPCredentials is the Schema for the gcpcredentials API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: GCPCredentialsSpec defines the desired state of GCPCredentials
          properties:
            key:
              description: Key is the credential used to create GCP projects You must
                create a service account with resourcemanager.projectCreator and billing.user
                roles at the organization level and use the JSON payload here
              type: string
            organizationId:
              description: Organization is the GCP org you wish the projects to reside
                within
              type: string
            projectId:
              description: ProjectId is the GCP project ID these credentials belong
                to
              type: string
          required:
          - key
          - organizationId
          - projectId
          type: object
        status:
          description: GCPCredentialsStatus defines the observed state of GCPCredentials
          properties:
            status:
              description: Status provides a overall status
              type: string
            verified:
              description: Verified checks that the credentials are ok and valid
              type: boolean
          required:
          - status
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
