apiVersion: apps/v1
kind: Deployment
metadata:
  name: gcp-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: gcp-operator
  template:
    metadata:
      labels:
        name: gcp-operator
    spec:
      serviceAccountName: gcp-operator
      containers:
        - name: gcp-operator
          image: quay.io/appvia/gcp-operator
          command:
          - gcp-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "gcp-operator"
