
/*
 * Copyright (C) 2019 Rohith Jayawardene <gambol99@gmail.com>
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

// Code generated by go generate; DO NOT EDIT.
// This file was generated by github.com/appvia/hub-apis/cmd/schema-gen

package schema

import (
	"bytes"
	"encoding/json"
	"strings"

	apiextensions "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1"

	yaml "github.com/ghodss/yaml"
)

var (
	// Schema is the openapi schema
	Schema = `
definitions:
  GCPAdminProject:
    description: GCPAdminProject is the Schema for the gcpadminprojects API
    properties:
      apiVersion:
        description: 'APIVersion defines the versioned schema of this representation
          of an object. Servers should convert recognized schemas to the latest internal
          value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
        type: string
      kind:
        description: 'Kind is a string value representing the REST resource this object
          represents. Servers may infer this from the endpoint the client submits
          requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
        type: string
      metadata:
        type: object
      spec:
        description: GCPAdminProjectSpec defines the desired state of GCPAdminProject
        properties:
          billingAccountName:
            description: BillingAccountName is the resource name of the billing account
              associated with the project e.g. '012345-567890-ABCDEF'
            type: string
          parentId:
            description: ParentId is the type specific ID of the parent this project
              has
            type: string
          parentType:
            description: 'ParentType is the type of parent this project has Valid
              types are: "organization", "folder", and "project"'
            enum:
            - organization
            - folder
            - project
            type: string
          projectId:
            description: ProjectId is the GCP project ID
            type: string
          projectName:
            description: ProjectName is the GCP project name
            type: string
          serviceAccountName:
            description: ServiceAccountName is the name used when creating the service
              account e.g. 'hub-admin'
            type: string
          use:
            description: GCPAdminToken is a reference to the gcp token object to use
            properties:
              group:
                description: Group is the api group
                type: string
              kind:
                description: Kind is the name of the resource under the group
                type: string
              name:
                description: Name is name of the resource
                type: string
              namespace:
                description: Namespace is the location of the object
                type: string
              version:
                description: Version is the group version
                type: string
            required:
            - group
            - kind
            - name
            - namespace
            - version
            type: object
        required:
        - billingAccountName
        - parentId
        - parentType
        - projectId
        - projectName
        - serviceAccountName
        - use
        type: object
      status:
        description: GCPAdminProjectStatus defines the observed state of GCPAdminProject
        properties:
          status:
            description: Status provides a overall status
            type: string
        required:
        - status
        type: object
    type: object
  GCPAdminToken:
    description: GCPAdminToken is the Schema for the gcpadmintokens API
    properties:
      apiVersion:
        description: 'APIVersion defines the versioned schema of this representation
          of an object. Servers should convert recognized schemas to the latest internal
          value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
        type: string
      kind:
        description: 'Kind is a string value representing the REST resource this object
          represents. Servers may infer this from the endpoint the client submits
          requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
        type: string
      metadata:
        type: object
      spec:
        description: GCPAdminTokenSpec defines the desired state of GCPAdminToken
        properties:
          organizationId:
            description: Organization is the GCP org you wish the projects to reside
              within
            type: string
          projectId:
            description: ProjectId is the GCP project ID these credentials belong
              to
            type: string
          token:
            description: Token is the bearer token used to setup the initial GCP admin
              project and service account You must grab a token using 'gcloud auth
              print-access-token you@example.com'
            type: string
        required:
        - organizationId
        - projectId
        - token
        type: object
      status:
        description: GCPAdminTokenStatus defines the observed state of GCPAdminToken
        properties:
          status:
            description: Status provides a overall status
            type: string
          verified:
            description: Verified checks that the token is ok and valid
            type: boolean
        required:
        - status
        - verified
        type: object
    type: object
  GCPCredentials:
    description: GCPCredentials is the Schema for the gcpcredentials API
    properties:
      apiVersion:
        description: 'APIVersion defines the versioned schema of this representation
          of an object. Servers should convert recognized schemas to the latest internal
          value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
        type: string
      kind:
        description: 'Kind is a string value representing the REST resource this object
          represents. Servers may infer this from the endpoint the client submits
          requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
        type: string
      metadata:
        type: object
      spec:
        description: GCPCredentialsSpec defines the desired state of GCPCredentials
        properties:
          key:
            description: Key is the credential used to create GCP projects You must
              create a service account with resourcemanager.projectCreator and billing.user
              roles at the organization level and use the JSON payload here
            type: string
          organizationId:
            description: Organization is the GCP org you wish the projects to reside
              within
            type: string
          projectId:
            description: ProjectId is the GCP project ID these credentials belong
              to
            type: string
        required:
        - key
        - organizationId
        - projectId
        type: object
      status:
        description: GCPCredentialsStatus defines the observed state of GCPCredentials
        properties:
          status:
            description: Status provides a overall status
            type: string
          verified:
            description: Verified checks that the credentials are ok and valid
            type: boolean
        required:
        - status
        type: object
    type: object
  GCPProject:
    description: GCPProject is the Schema for the gcpprojects API
    properties:
      apiVersion:
        description: 'APIVersion defines the versioned schema of this representation
          of an object. Servers should convert recognized schemas to the latest internal
          value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
        type: string
      kind:
        description: 'Kind is a string value representing the REST resource this object
          represents. Servers may infer this from the endpoint the client submits
          requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
        type: string
      metadata:
        type: object
      spec:
        description: GCPProjectSpec defines the desired state of GCPProject
        properties:
          billingAccountName:
            description: BillingAccountName is the resource name of the billing account
              associated with the project
            type: string
          parentId:
            description: ParentId is the type specific ID of the parent this project
              has
            type: string
          parentType:
            description: 'ParentType is the type of parent this project has Valid
              types are: "organization", "folder", and "project"'
            enum:
            - organization
            - folder
            - project
            type: string
          projectId:
            description: ProjectId is the GCP project ID
            type: string
          projectName:
            description: ProjectName is the GCP project name
            type: string
          use:
            description: GCPCredentials is a reference to the gcp credentials object
              to use
            properties:
              group:
                description: Group is the api group
                type: string
              kind:
                description: Kind is the name of the resource under the group
                type: string
              name:
                description: Name is name of the resource
                type: string
              namespace:
                description: Namespace is the location of the object
                type: string
              version:
                description: Version is the group version
                type: string
            required:
            - group
            - kind
            - name
            - namespace
            - version
            type: object
        required:
        - billingAccountName
        - parentId
        - parentType
        - projectId
        - projectName
        - use
        type: object
      status:
        description: GCPProjectStatus defines the observed state of GCPProject
        properties:
          status:
            description: Status provides a overall status
            type: string
        required:
        - status
        type: object
    type: object
`

	// CustomResourceDefinitions are the custom resources types
	CustomResourceDefinitions = `
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: gcpadminprojects.gcp.compute.hub.appvia.io
spec:
  group: gcp.compute.hub.appvia.io
  names:
    kind: GCPAdminProject
    listKind: GCPAdminProjectList
    plural: gcpadminprojects
    singular: gcpadminproject
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: GCPAdminProject is the Schema for the gcpadminprojects API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: GCPAdminProjectSpec defines the desired state of GCPAdminProject
          properties:
            billingAccountName:
              description: BillingAccountName is the resource name of the billing
                account associated with the project e.g. '012345-567890-ABCDEF'
              type: string
            parentId:
              description: ParentId is the type specific ID of the parent this project
                has
              type: string
            parentType:
              description: 'ParentType is the type of parent this project has Valid
                types are: "organization", "folder", and "project"'
              enum:
              - organization
              - folder
              - project
              type: string
            projectId:
              description: ProjectId is the GCP project ID
              type: string
            projectName:
              description: ProjectName is the GCP project name
              type: string
            serviceAccountName:
              description: ServiceAccountName is the name used when creating the service
                account e.g. 'hub-admin'
              type: string
            use:
              description: GCPAdminToken is a reference to the gcp token object to
                use
              properties:
                group:
                  description: Group is the api group
                  type: string
                kind:
                  description: Kind is the name of the resource under the group
                  type: string
                name:
                  description: Name is name of the resource
                  type: string
                namespace:
                  description: Namespace is the location of the object
                  type: string
                version:
                  description: Version is the group version
                  type: string
              required:
              - group
              - kind
              - name
              - namespace
              - version
              type: object
          required:
          - billingAccountName
          - parentId
          - parentType
          - projectId
          - projectName
          - serviceAccountName
          - use
          type: object
        status:
          description: GCPAdminProjectStatus defines the observed state of GCPAdminProject
          properties:
            status:
              description: Status provides a overall status
              type: string
          required:
          - status
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: gcpadmintokens.gcp.compute.hub.appvia.io
spec:
  group: gcp.compute.hub.appvia.io
  names:
    kind: GCPAdminToken
    listKind: GCPAdminTokenList
    plural: gcpadmintokens
    singular: gcpadmintoken
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: GCPAdminToken is the Schema for the gcpadmintokens API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: GCPAdminTokenSpec defines the desired state of GCPAdminToken
          properties:
            organizationId:
              description: Organization is the GCP org you wish the projects to reside
                within
              type: string
            projectId:
              description: ProjectId is the GCP project ID these credentials belong
                to
              type: string
            token:
              description: Token is the bearer token used to setup the initial GCP
                admin project and service account You must grab a token using 'gcloud
                auth print-access-token you@example.com'
              type: string
          required:
          - organizationId
          - projectId
          - token
          type: object
        status:
          description: GCPAdminTokenStatus defines the observed state of GCPAdminToken
          properties:
            status:
              description: Status provides a overall status
              type: string
            verified:
              description: Verified checks that the token is ok and valid
              type: boolean
          required:
          - status
          - verified
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: gcpcredentials.gcp.compute.hub.appvia.io
spec:
  group: gcp.compute.hub.appvia.io
  names:
    kind: GCPCredentials
    listKind: GCPCredentialsList
    plural: gcpcredentials
    singular: gcpcredentials
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: GCPCredentials is the Schema for the gcpcredentials API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: GCPCredentialsSpec defines the desired state of GCPCredentials
          properties:
            key:
              description: Key is the credential used to create GCP projects You must
                create a service account with resourcemanager.projectCreator and billing.user
                roles at the organization level and use the JSON payload here
              type: string
            organizationId:
              description: Organization is the GCP org you wish the projects to reside
                within
              type: string
            projectId:
              description: ProjectId is the GCP project ID these credentials belong
                to
              type: string
          required:
          - key
          - organizationId
          - projectId
          type: object
        status:
          description: GCPCredentialsStatus defines the observed state of GCPCredentials
          properties:
            status:
              description: Status provides a overall status
              type: string
            verified:
              description: Verified checks that the credentials are ok and valid
              type: boolean
          required:
          - status
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: gcpprojects.gcp.compute.hub.appvia.io
spec:
  group: gcp.compute.hub.appvia.io
  names:
    kind: GCPProject
    listKind: GCPProjectList
    plural: gcpprojects
    singular: gcpproject
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: GCPProject is the Schema for the gcpprojects API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: GCPProjectSpec defines the desired state of GCPProject
          properties:
            billingAccountName:
              description: BillingAccountName is the resource name of the billing
                account associated with the project
              type: string
            parentId:
              description: ParentId is the type specific ID of the parent this project
                has
              type: string
            parentType:
              description: 'ParentType is the type of parent this project has Valid
                types are: "organization", "folder", and "project"'
              enum:
              - organization
              - folder
              - project
              type: string
            projectId:
              description: ProjectId is the GCP project ID
              type: string
            projectName:
              description: ProjectName is the GCP project name
              type: string
            use:
              description: GCPCredentials is a reference to the gcp credentials object
                to use
              properties:
                group:
                  description: Group is the api group
                  type: string
                kind:
                  description: Kind is the name of the resource under the group
                  type: string
                name:
                  description: Name is name of the resource
                  type: string
                namespace:
                  description: Namespace is the location of the object
                  type: string
                version:
                  description: Version is the group version
                  type: string
              required:
              - group
              - kind
              - name
              - namespace
              - version
              type: object
          required:
          - billingAccountName
          - parentId
          - parentType
          - projectId
          - projectName
          - use
          type: object
        status:
          description: GCPProjectStatus defines the observed state of GCPProject
          properties:
            status:
              description: Status provides a overall status
              type: string
          required:
          - status
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
`
)

// ConvertToJSON converts the CRD defitions into a swagger manifest
func ConvertToJSON() apiextensions.JSON {
	encoded, err := yaml.YAMLToJSON([]byte(Schema))
	if err != nil {
		panic("invalid crd schema")
	}

	return apiextensions.JSON{Raw: encoded}
}

// GetCustomResourceDefinitions returns all the CRDs for registation
func GetCustomResourceDefinitions() []*apiextensions.CustomResourceDefinition{
	var list []*apiextensions.CustomResourceDefinition

	for _, document := range strings.Split(CustomResourceDefinitions, "---") {
		decoded, err := yaml.YAMLToJSON([]byte(document))
		if err != nil {
			panic("failed to parse the custom resource definition")
		}

		crd := &apiextensions.CustomResourceDefinition{}
		if err := json.NewDecoder(bytes.NewReader(decoded)).Decode(crd); err != nil {
			panic("failed to parse the custom resource definition yaml")
		}

		list = append(list, crd)
	}

	return list
}

