// +build !ignore_autogenerated

// This file was autogenerated by openapi-gen. Do not edit it manually!

package v1alpha1

import (
	spec "github.com/go-openapi/spec"
	common "k8s.io/kube-openapi/pkg/common"
)

func GetOpenAPIDefinitions(ref common.ReferenceCallback) map[string]common.OpenAPIDefinition {
	return map[string]common.OpenAPIDefinition{
		"github.com/appvia/gcp-operator/pkg/apis/gcp/v1alpha1.GCPCredentials":       schema_pkg_apis_gcp_v1alpha1_GCPCredentials(ref),
		"github.com/appvia/gcp-operator/pkg/apis/gcp/v1alpha1.GCPCredentialsSpec":   schema_pkg_apis_gcp_v1alpha1_GCPCredentialsSpec(ref),
		"github.com/appvia/gcp-operator/pkg/apis/gcp/v1alpha1.GCPCredentialsStatus": schema_pkg_apis_gcp_v1alpha1_GCPCredentialsStatus(ref),
		"github.com/appvia/gcp-operator/pkg/apis/gcp/v1alpha1.GCPProject":           schema_pkg_apis_gcp_v1alpha1_GCPProject(ref),
		"github.com/appvia/gcp-operator/pkg/apis/gcp/v1alpha1.GCPProjectSpec":       schema_pkg_apis_gcp_v1alpha1_GCPProjectSpec(ref),
		"github.com/appvia/gcp-operator/pkg/apis/gcp/v1alpha1.GCPProjectStatus":     schema_pkg_apis_gcp_v1alpha1_GCPProjectStatus(ref),
	}
}

func schema_pkg_apis_gcp_v1alpha1_GCPCredentials(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "GCPCredentials is the Schema for the gcpcredentials API",
				Type:        []string{"object"},
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/appvia/gcp-operator/pkg/apis/gcp/v1alpha1.GCPCredentialsSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/appvia/gcp-operator/pkg/apis/gcp/v1alpha1.GCPCredentialsStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"github.com/appvia/gcp-operator/pkg/apis/gcp/v1alpha1.GCPCredentialsSpec", "github.com/appvia/gcp-operator/pkg/apis/gcp/v1alpha1.GCPCredentialsStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_pkg_apis_gcp_v1alpha1_GCPCredentialsSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "GCPCredentialsSpec defines the desired state of GCPCredentials",
				Type:        []string{"object"},
			},
		},
	}
}

func schema_pkg_apis_gcp_v1alpha1_GCPCredentialsStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "GCPCredentialsStatus defines the observed state of GCPCredentials",
				Type:        []string{"object"},
			},
		},
	}
}

func schema_pkg_apis_gcp_v1alpha1_GCPProject(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "GCPProject is the Schema for the gcpprojects API",
				Type:        []string{"object"},
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/appvia/gcp-operator/pkg/apis/gcp/v1alpha1.GCPProjectSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/appvia/gcp-operator/pkg/apis/gcp/v1alpha1.GCPProjectStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"github.com/appvia/gcp-operator/pkg/apis/gcp/v1alpha1.GCPProjectSpec", "github.com/appvia/gcp-operator/pkg/apis/gcp/v1alpha1.GCPProjectStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_pkg_apis_gcp_v1alpha1_GCPProjectSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "GCPProjectSpec defines the desired state of GCPProject",
				Type:        []string{"object"},
			},
		},
	}
}

func schema_pkg_apis_gcp_v1alpha1_GCPProjectStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "GCPProjectStatus defines the observed state of GCPProject",
				Type:        []string{"object"},
			},
		},
	}
}
